language: csharp

mono: 5.18.0
dotnet: 2.1.401

install:
  # workaround for missing .net 4.6.1 targing pack
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.6.1-api/

script:
  - dotnet pack -v n
  - dotnet test -v n

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode9
